apiVersion: v1
kind: Config
clusters:
- cluster:
    server: https://192.168.49.2:8443
    certificate-authority: /minikube/ca.crt
  name: minikube
users:
- name: minikube
  user:
    client-certificate: /minikube/profiles/minikube/client.crt
    client-key: /minikube/profiles/minikube/client.key
contexts:
- context:
    cluster: minikube
    user: minikube
  name: minikube
current-context: minikube
